def menu():
    print("*** Bem vindo ao Bom Appetit Sistema ***")
    print("\n --- Menu ---")
    print("1. Cadastrar Produto")
    print("2. Buscar Produto")
    print("3. Listar Produtos")
    print("4. Remover Produto")
    print("5. Editar produto")
    print("6. Relizar pedido")
    print("7. Listar Itens do Pedido")
    print("8. Cadastrar Atendente")
    print("9. Listar Atendentes")
    print("10. Abrir Mesa")
    print("11. Listar Mesas")
    print("12. Fechar Mesa")
    print("13. Relatório de Vendas")
    print("0. Sair")
    escolha = input("Escolha uma opção: ")
    return escolha
